name: CMake

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-under-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Checkout MAVSDK
        uses: actions/checkout@v3
        with:
          repository: GoerLabs/MAVSDK
          ref: develop
          path: MAVSDK
          submodules: recursive

      - name: Config MAVSDK
        run: sudo cmake -S ${{github.workspace}}/MAVSDK -B ${{github.workspace}}/mavsdk-build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
      - name: Buidl and install MAVSDK
        run: sudo cmake --build ${{github.workspace}}/mavsdk-build --target install

      - name: Checkout MAVCam
        uses: actions/checkout@v3
        with:
          path: MAVCam
          submodules: recursive

      - name: Configure MAVCam 
        run: sudo cmake -S ${{github.workspace}}/MAVCam -B ${{github.workspace}}/mavcam-build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build MAVCam
        run: sudo cmake --build ${{github.workspace}}/mavcam-build
